"""
saqqara — document substrate kernels: typed trees with provenance on every node.

A document is an object before it is a fragment. This family reads a document
into a typed tree, keeps an exact citation on every node, and recognises the
structures a reader sees — sections, tables, header bands, label tilings —
by ordered hard rules that abstain rather than guess.

Stage 1 (Collection):  adapters — pdf / docx / xlsx / pptx / md, raw facts only
Stage 2 (Analysis):    analyzers — tables, header bands, islands, sections
Stage 3 (Reporting):   views — lazy projections over the tree, provenance intact

Layers:
  model      Node, KindRegistry, Locator, Provenance, Tree, stable JSON
  adapters   one per format; each emits Mastaba raw facts, never structure
  analyzers  chained tree -> tree + decomposed trace
  views      blocks, anchors, chains, records — computed, never stored
  kernel     the single KOAS kernel facade over the layers above

Design rules, enforced by the gates in tests/saqqara/ and specified in SPEC.md:
  - no node without provenance;
  - abstention is an object carried by the output, never a default value;
  - segmentation and header recognition use ordered hard rules and expose a
    decomposed trace; scores are never blended;
  - what is dropped is counted and described, never silently discarded;
  - fixtures are generated by code; no document is ever committed.

Status: gated against SPEC.md (153 propositions; tests/saqqara). Every layer below
is specified in SPEC.md before it is implemented; a function that no proposition
justifies does not belong here.

Author: Olivier Vitrac, PhD, HDR | olivier.vitrac@adservio.fr | Adservio | 2026-08-27
"""
