"""
RAGIX Core - Shared orchestrator and tooling for RAGIX agents

Author: Olivier Vitrac, PhD, HDR | olivier.vitrac@adservio.fr | Adservio | 2025-11-28
"""

# Import version from centralized source
from .version import __version__, get_version, get_version_info, get_banner

from .llm_backends import (
    SovereigntyStatus,
    BaseLLM,
    OllamaLLM,
    ClaudeLLM,
    OpenAILLM,
    create_llm_backend,
    get_backend_from_env,
)
from .tools_shell import ShellSandbox, CommandResult
from .logging_utils import AgentLogger, LogLevel, mask_secrets
from .profiles import (
    Profile,
    compute_dry_run_from_profile,
    get_profile_restrictions,
    merge_denylist_from_config,
    DANGEROUS_PATTERNS,
    GIT_DESTRUCTIVE_PATTERNS,
)
from .orchestrator import (
    extract_json_object,
    extract_json_with_diagnostics,
    validate_action_schema,
    create_retry_prompt,
)
from .retrieval import Retriever, GrepRetriever, RetrievalResult, format_retrieval_results
from .agent_graph import (
    AgentNode,
    AgentEdge,
    AgentGraph,
    NodeStatus,
    TransitionCondition,
    create_linear_workflow,
)
from .graph_executor import (
    GraphExecutor,
    SyncGraphExecutor,
    ExecutionContext,
    ExecutionResult,
    ExecutionStatus,
)
from .agents import (
    BaseAgent,
    AgentCapability,
    CodeAgent,
    DocAgent,
    GitAgent,
    TestAgent,
)
from .chunking import (
    ChunkType,
    CodeChunk,
    PythonChunker,
    MarkdownChunker,
    GenericChunker,
    chunk_file,
)
from .embeddings import (
    EmbeddingBackend,
    EmbeddingConfig,
    SentenceTransformerBackend,
    DummyEmbeddingBackend,
    ChunkEmbedding,
    embed_code_chunks,
    save_embeddings,
    load_embeddings,
    create_embedding_backend,
)
from .vector_index import (
    SearchResult,
    VectorIndex,
    NumpyVectorIndex,
    FAISSVectorIndex,
    create_vector_index,
    build_index_from_embeddings,
)
from .batch_mode import (
    BatchExitCode,
    BatchConfig,
    WorkflowResult,
    BatchResult,
    BatchExecutor,
    run_batch_sync,
)
from .secrets_vault import (
    SecretMetadata,
    SecretProvider,
    InMemoryVault,
    EncryptedFileVault,
    AccessPolicy,
    VaultManager,
    create_vault,
)
from .tool_registry import (
    ToolCategory,
    ToolPermission,
    ToolParameter,
    ToolDefinition,
    ToolRegistry,
    get_tool_registry,
)
from .agent_llm_bridge import (
    ExecutionState,
    ToolCall,
    ToolResult,
    ExecutionStep,
    AgentExecutionResult,
    ToolExecutor,
    LLMAgentExecutor,
    create_agent_executor,
)
from .prompt_templates import (
    TaskType,
    FewShotExample,
    PromptTemplate,
    get_template,
    detect_task_type,
    build_prompt,
)
from .bm25_index import (
    BM25Document,
    BM25SearchResult,
    Tokenizer,
    BM25Index,
    build_bm25_index_from_chunks,
)
from .hybrid_search import (
    FusionStrategy,
    HybridSearchResult,
    HybridSearchEngine,
    create_hybrid_search_engine,
)
# Alias for backwards compatibility
create_hybrid_engine = create_hybrid_search_engine
from .workflow_templates import (
    WorkflowParameter,
    WorkflowStep,
    WorkflowTemplate,
    TemplateManager,
    get_template_manager,
    list_builtin_templates,
    BUILTIN_TEMPLATES,
)
from .caching import (
    CacheEntry,
    CacheBackend,
    InMemoryCache,
    DiskCache,
    LLMCache,
    ToolResultCache,
    create_llm_cache,
)
from .graph_executor import StreamEvent
from .monitoring import (
    MetricType,
    HealthStatus,
    Metric,
    HealthCheck,
    MetricsCollector,
    HealthChecker,
    AgentMonitor,
    RateLimiter,
    CircuitBreaker,
    get_metrics,
    get_health_checker,
    get_agent_monitor,
    check_ollama_health,
    check_disk_space,
    check_memory_usage,
)
from .resilience import (
    BackoffStrategy,
    RetryConfig,
    retry,
    retry_async,
    RetryContext,
    FallbackChain,
    Timeout,
    Bulkhead,
    GracefulDegradation,
    with_timeout,
    with_retry,
    with_fallback,
)
from .config import (
    RAGIXConfig,
    LLMConfig,
    MCPConfig,
    SafetyConfig,
    SearchConfig,
    LoggingConfig,
    WebUIConfig,
    HardwareConfig,
    load_config,
    save_config,
    get_config,
    reload_config,
    find_config_file,
)
from .agent_config import (
    AgentMode,
    AgentRole,
    AgentConfig,
    OllamaModel,
    detect_ollama_models,
    get_agent_persona,
    AGENT_PERSONAS,
    MODEL_REGISTRY,
    MODEL_CONTEXT_LIMITS,
    DEFAULT_CONTEXT_LIMIT,
    get_model_context_limit,
    get_model_info,
)
from .ollama_client import (
    OllamaClient,
    ModelInfo,
    get_ollama_client,
    get_dynamic_context_limit,
)
from .reasoning import (
    TaskComplexity,
    EpisodeEntry,
    EpisodicMemory,
    PlanStep,
    Plan,
    ReasoningLoop,
    # v0.23 Graph-based reasoning
    ReasoningStrategy,
    GraphReasoningLoop,
    create_reasoning_loop,
    get_reasoning_strategy,
)
# Reasoning Graph v2 types
from .reasoning_types import (
    StepStatus,
    StopReason,
    ReasoningState,
    ReasoningEvent,
    ReflectionAttempt,
    get_max_reflections,
)
from .reasoning_types import (
    PlanStep as GraphPlanStep,
    Plan as GraphPlan,
    TaskComplexity as GraphTaskComplexity,
)
# Experience Corpus
from .experience_corpus import (
    ExperienceCorpus,
    HybridExperienceCorpus,
    get_hybrid_corpus,
)
# Reasoning Graph
from .reasoning_graph import (
    BaseNode,
    ReasoningGraph,
    ClassifyNode,
    DirectExecNode,
    PlanNode,
    ExecuteNode,
    ReflectNode,
    VerifyNode,
    RespondNode,
    create_reasoning_graph,
)
from .knowledge_base import (
    CommandPattern,
    ReasoningRule,
    KnowledgeBase,
    get_knowledge_base,
    reset_knowledge_base,
)
from .log_integrity import (
    LogEntry,
    LogIntegrityReport,
    compute_hash,
    compute_file_hash,
    ChainedLogHasher,
    SimpleFileHasher,
    AuditLogManager,
)
from .plugin_system import (
    PluginType,
    TrustLevel,
    PluginCapability,
    PluginTool,
    PluginWorkflow,
    PluginManifest,
    LoadedPlugin,
    PluginManager,
    get_plugin_manager,
    compute_plugin_checksum,
)
from .swe_workflows import (
    WorkflowState,
    ChunkState,
    ChunkResult,
    WorkflowCheckpoint,
    ChunkConfig,
    ChunkedWorkflow,
    FileProcessingWorkflow,
    CodeReviewWorkflow,
    MigrationWorkflow,
    list_checkpoints,
    resume_workflow,
)
from .sandbox_base import (
    SandboxType,
    SandboxCapability,
    SandboxConfig,
    ExecutionResult,
    BaseSandbox,
    SandboxRegistry,
    HybridSandbox,
    ShellSandboxAdapter,
    create_sandbox,
    get_sandbox_registry,
)
# Import tool registry additions
from .tool_registry import (
    ToolProvider,
    sync_plugins_to_registry,
)
# WASP executor
from .wasp_executor import (
    WaspExecutionResult,
    WaspExecutor,
    get_wasp_executor,
    execute_wasp_action,
)
# AST Analysis
from .ast_base import (
    Language,
    NodeType,
    Visibility,
    SourceLocation,
    TypeInfo,
    Symbol,
    ASTNode,
    ASTBackend,
    get_ast_registry,
    format_ast_tree,
)
from .ast_python import PythonASTBackend, get_python_backend
# Import Java backend to auto-register it (requires javalang)
try:
    from .ast_java import JavaASTBackend, get_java_backend, is_java_available
except ImportError:
    JavaASTBackend = None
    get_java_backend = lambda: None
    is_java_available = lambda: False
from .ast_query import (
    QueryType,
    QueryPredicate,
    ASTQuery,
    QueryMatch,
    parse_query,
    execute_query,
    execute_query_on_ast,
)
from .dependencies import (
    DependencyType,
    Dependency,
    DependencyGraph,
    DependencyStats,
    build_dependency_graph,
)
from .maven import (
    MavenCoordinate,
    MavenDependency,
    MavenProject,
    MavenParser,
    parse_pom,
    scan_maven_projects,
)
from .code_metrics import (
    ComplexityLevel,
    MethodMetrics,
    ClassMetrics,
    FileMetrics,
    ProjectMetrics,
    calculate_project_metrics,
    calculate_metrics_from_graph,
)
from .ast_viz import (
    VizConfig,
    LayoutDirection,
    ColorScheme,
    DotRenderer,
    MermaidRenderer,
    D3Renderer,
    HTMLRenderer,
    VisHTMLRenderer,
    VIS_RENDERER_THRESHOLD,
    get_optimal_renderer,
    DSMRenderer,
    RadialExplorer,
    graph_to_dot,
    graph_to_mermaid,
    graph_to_html,
)
# Advanced Visualizations
from .ast_viz_advanced import (
    TreemapMetric,
    TreemapConfig,
    TreemapRenderer,
    SunburstConfig,
    SunburstRenderer,
    ChordConfig,
    ChordRenderer,
)
# Report Generation
try:
    from .report_engine import (
        ReportFormat,
        ReportType,
        ComplianceStandard,
        Finding,
        ReportSection,
        ReportConfig,
        ReportData,
        MavenData,
        SonarData,
        BaseReportGenerator,
        ExecutiveSummaryGenerator,
        TechnicalAuditGenerator,
        ComplianceReportGenerator,
        ReportEngine,
        get_report_engine,
        generate_executive_summary,
        generate_technical_audit,
        generate_compliance_report,
    )
    REPORTS_AVAILABLE = True
except ImportError:
    REPORTS_AVAILABLE = False

# Analysis Cache
from .analysis_cache import (
    CacheMetadata,
    CachedAnalysis,
    AnalysisCache,
    get_cache,
    get_or_analyze,
    TRACKED_EXTENSIONS,
    EXCLUDED_DIRS,
)

from .maven_cache import (
    MavenCacheMetadata,
    CachedMavenAnalysis,
    MavenCache,
    get_maven_cache,
)

from .sonar_cache import (
    SonarCacheMetadata,
    CachedSonarAnalysis,
    SonarCache,
    get_sonar_cache,
    DEFAULT_TTL_SECONDS,
)

__all__ = [
    # LLM Backends
    "SovereigntyStatus",
    "BaseLLM",
    "OllamaLLM",
    "ClaudeLLM",
    "OpenAILLM",
    "create_llm_backend",
    "get_backend_from_env",
    "ShellSandbox",
    "CommandResult",
    "AgentLogger",
    "LogLevel",
    "mask_secrets",
    "Profile",
    "compute_dry_run_from_profile",
    "get_profile_restrictions",
    "merge_denylist_from_config",
    "extract_json_object",
    "extract_json_with_diagnostics",
    "validate_action_schema",
    "create_retry_prompt",
    "Retriever",
    "GrepRetriever",
    "RetrievalResult",
    "format_retrieval_results",
    "AgentNode",
    "AgentEdge",
    "AgentGraph",
    "NodeStatus",
    "TransitionCondition",
    "create_linear_workflow",
    "GraphExecutor",
    "SyncGraphExecutor",
    "ExecutionContext",
    "ExecutionResult",
    "ExecutionStatus",
    "BaseAgent",
    "AgentCapability",
    "CodeAgent",
    "DocAgent",
    "GitAgent",
    "TestAgent",
    "ChunkType",
    "CodeChunk",
    "PythonChunker",
    "MarkdownChunker",
    "GenericChunker",
    "chunk_file",
    "EmbeddingBackend",
    "EmbeddingConfig",
    "SentenceTransformerBackend",
    "DummyEmbeddingBackend",
    "ChunkEmbedding",
    "embed_code_chunks",
    "save_embeddings",
    "load_embeddings",
    "create_embedding_backend",
    "SearchResult",
    "VectorIndex",
    "NumpyVectorIndex",
    "FAISSVectorIndex",
    "create_vector_index",
    "build_index_from_embeddings",
    "BatchExitCode",
    "BatchConfig",
    "WorkflowResult",
    "BatchResult",
    "BatchExecutor",
    "run_batch_sync",
    "SecretMetadata",
    "SecretProvider",
    "InMemoryVault",
    "EncryptedFileVault",
    "AccessPolicy",
    "VaultManager",
    "create_vault",
    "ToolCategory",
    "ToolPermission",
    "ToolParameter",
    "ToolDefinition",
    "ToolRegistry",
    "get_tool_registry",
    "ExecutionState",
    "ToolCall",
    "ToolResult",
    "ExecutionStep",
    "AgentExecutionResult",
    "ToolExecutor",
    "LLMAgentExecutor",
    "create_agent_executor",
    "TaskType",
    "FewShotExample",
    "PromptTemplate",
    "get_template",
    "detect_task_type",
    "build_prompt",
    "DANGEROUS_PATTERNS",
    "GIT_DESTRUCTIVE_PATTERNS",
    # BM25 Index
    "BM25Document",
    "BM25SearchResult",
    "Tokenizer",
    "BM25Index",
    "build_bm25_index_from_chunks",
    # Hybrid Search
    "FusionStrategy",
    "HybridSearchResult",
    "HybridSearchEngine",
    "create_hybrid_search_engine",
    "create_hybrid_engine",  # alias
    # Workflow Templates
    "WorkflowParameter",
    "WorkflowStep",
    "WorkflowTemplate",
    "TemplateManager",
    "get_template_manager",
    "list_builtin_templates",
    "BUILTIN_TEMPLATES",
    # Caching
    "CacheEntry",
    "CacheBackend",
    "InMemoryCache",
    "DiskCache",
    "LLMCache",
    "ToolResultCache",
    "create_llm_cache",
    # Streaming
    "StreamEvent",
    # Monitoring
    "MetricType",
    "HealthStatus",
    "Metric",
    "HealthCheck",
    "MetricsCollector",
    "HealthChecker",
    "AgentMonitor",
    "RateLimiter",
    "CircuitBreaker",
    "get_metrics",
    "get_health_checker",
    "get_agent_monitor",
    "check_ollama_health",
    "check_disk_space",
    "check_memory_usage",
    # Resilience
    "BackoffStrategy",
    "RetryConfig",
    "retry",
    "retry_async",
    "RetryContext",
    "FallbackChain",
    "Timeout",
    "Bulkhead",
    "GracefulDegradation",
    "with_timeout",
    "with_retry",
    "with_fallback",
    # Configuration
    "RAGIXConfig",
    "LLMConfig",
    "MCPConfig",
    "SafetyConfig",
    "SearchConfig",
    "LoggingConfig",
    "WebUIConfig",
    "HardwareConfig",
    "load_config",
    "save_config",
    "get_config",
    "reload_config",
    "find_config_file",
    # Agent Configuration (Planner-Worker-Verifier)
    "AgentMode",
    "AgentRole",
    "AgentConfig",
    "OllamaModel",
    "detect_ollama_models",
    "get_agent_persona",
    "AGENT_PERSONAS",
    "MODEL_REGISTRY",
    # Reasoning Loop (Planner-Worker-Verifier)
    "TaskComplexity",
    "EpisodeEntry",
    "EpisodicMemory",
    "PlanStep",
    "Plan",
    "ReasoningLoop",
    # v0.23 Reflective Reasoning Graph
    "ReasoningStrategy",
    "GraphReasoningLoop",
    "create_reasoning_loop",
    "get_reasoning_strategy",
    "StepStatus",
    "StopReason",
    "ReasoningState",
    "ReasoningEvent",
    "ReflectionAttempt",
    "get_max_reflections",
    "GraphPlanStep",
    "GraphPlan",
    "GraphTaskComplexity",
    # Experience Corpus
    "ExperienceCorpus",
    "HybridExperienceCorpus",
    "get_hybrid_corpus",
    # Reasoning Graph Nodes
    "BaseNode",
    "ReasoningGraph",
    "ClassifyNode",
    "DirectExecNode",
    "PlanNode",
    "ExecuteNode",
    "ReflectNode",
    "VerifyNode",
    "RespondNode",
    "create_reasoning_graph",
    # Knowledge Base
    "CommandPattern",
    "ReasoningRule",
    "KnowledgeBase",
    "get_knowledge_base",
    "reset_knowledge_base",
    # Log Integrity
    "LogEntry",
    "LogIntegrityReport",
    "compute_hash",
    "compute_file_hash",
    "ChainedLogHasher",
    "SimpleFileHasher",
    "AuditLogManager",
    # Plugin System
    "PluginType",
    "TrustLevel",
    "PluginCapability",
    "PluginTool",
    "PluginWorkflow",
    "PluginManifest",
    "LoadedPlugin",
    "PluginManager",
    "get_plugin_manager",
    "compute_plugin_checksum",
    # SWE Workflows
    "WorkflowState",
    "ChunkState",
    "ChunkResult",
    "WorkflowCheckpoint",
    "ChunkConfig",
    "ChunkedWorkflow",
    "FileProcessingWorkflow",
    "CodeReviewWorkflow",
    "MigrationWorkflow",
    "list_checkpoints",
    "resume_workflow",
    # Sandbox Abstraction
    "SandboxType",
    "SandboxCapability",
    "SandboxConfig",
    "ExecutionResult",
    "BaseSandbox",
    "SandboxRegistry",
    "HybridSandbox",
    "ShellSandboxAdapter",
    "create_sandbox",
    "get_sandbox_registry",
    # Tool Registry Additions
    "ToolProvider",
    "sync_plugins_to_registry",
    # WASP Executor
    "WaspExecutionResult",
    "WaspExecutor",
    "get_wasp_executor",
    "execute_wasp_action",
    # AST Analysis
    "Language",
    "NodeType",
    "Visibility",
    "SourceLocation",
    "TypeInfo",
    "Symbol",
    "ASTNode",
    "ASTBackend",
    "get_ast_registry",
    "format_ast_tree",
    "PythonASTBackend",
    "get_python_backend",
    "QueryType",
    "QueryPredicate",
    "ASTQuery",
    "QueryMatch",
    "parse_query",
    "execute_query",
    "execute_query_on_ast",
    "DependencyType",
    "Dependency",
    "DependencyGraph",
    "DependencyStats",
    "build_dependency_graph",
    # Maven
    "MavenCoordinate",
    "MavenDependency",
    "MavenProject",
    "MavenParser",
    "parse_pom",
    "scan_maven_projects",
    # Code Metrics
    "ComplexityLevel",
    "MethodMetrics",
    "ClassMetrics",
    "FileMetrics",
    "ProjectMetrics",
    "calculate_project_metrics",
    "calculate_metrics_from_graph",
    # AST Visualization
    "VizConfig",
    "LayoutDirection",
    "ColorScheme",
    "DotRenderer",
    "MermaidRenderer",
    "D3Renderer",
    "HTMLRenderer",
    "VisHTMLRenderer",
    "VIS_RENDERER_THRESHOLD",
    "get_optimal_renderer",
    "DSMRenderer",
    "RadialExplorer",
    "graph_to_dot",
    "graph_to_mermaid",
    "graph_to_html",
    # Advanced Visualizations
    "TreemapMetric",
    "TreemapConfig",
    "TreemapRenderer",
    "SunburstConfig",
    "SunburstRenderer",
    "ChordConfig",
    "ChordRenderer",
    # Report Generation
    "ReportFormat",
    "ReportType",
    "ComplianceStandard",
    "Finding",
    "ReportSection",
    "ReportConfig",
    "ReportData",
    "MavenData",
    "SonarData",
    "BaseReportGenerator",
    "ExecutiveSummaryGenerator",
    "TechnicalAuditGenerator",
    "ComplianceReportGenerator",
    "ReportEngine",
    "get_report_engine",
    "generate_executive_summary",
    "generate_technical_audit",
    "generate_compliance_report",
    "REPORTS_AVAILABLE",
    # Analysis Cache
    "CacheMetadata",
    "CachedAnalysis",
    "AnalysisCache",
    "get_cache",
    "get_or_analyze",
    "TRACKED_EXTENSIONS",
    "EXCLUDED_DIRS",
    # Maven Cache
    "MavenCacheMetadata",
    "CachedMavenAnalysis",
    "MavenCache",
    "get_maven_cache",
    # Sonar Cache
    "SonarCacheMetadata",
    "CachedSonarAnalysis",
    "SonarCache",
    "get_sonar_cache",
    "DEFAULT_TTL_SECONDS",
]
