"""
RAGIX Core - Shared orchestrator and tooling for RAGIX agents

Author: Olivier Vitrac, PhD, HDR | olivier.vitrac@adservio.fr | Adservio | 2025-11-26
"""

__version__ = "0.9.0"

from .llm_backends import (
    SovereigntyStatus,
    BaseLLM,
    OllamaLLM,
    ClaudeLLM,
    OpenAILLM,
    create_llm_backend,
    get_backend_from_env,
)
from .tools_shell import ShellSandbox, CommandResult
from .logging_utils import AgentLogger, LogLevel, mask_secrets
from .profiles import (
    Profile,
    compute_dry_run_from_profile,
    get_profile_restrictions,
    merge_denylist_from_config,
    DANGEROUS_PATTERNS,
    GIT_DESTRUCTIVE_PATTERNS,
)
from .orchestrator import (
    extract_json_object,
    extract_json_with_diagnostics,
    validate_action_schema,
    create_retry_prompt,
)
from .retrieval import Retriever, GrepRetriever, RetrievalResult, format_retrieval_results
from .agent_graph import (
    AgentNode,
    AgentEdge,
    AgentGraph,
    NodeStatus,
    TransitionCondition,
    create_linear_workflow,
)
from .graph_executor import (
    GraphExecutor,
    SyncGraphExecutor,
    ExecutionContext,
    ExecutionResult,
    ExecutionStatus,
)
from .agents import (
    BaseAgent,
    AgentCapability,
    CodeAgent,
    DocAgent,
    GitAgent,
    TestAgent,
)
from .chunking import (
    ChunkType,
    CodeChunk,
    PythonChunker,
    MarkdownChunker,
    GenericChunker,
    chunk_file,
)
from .embeddings import (
    EmbeddingBackend,
    EmbeddingConfig,
    SentenceTransformerBackend,
    DummyEmbeddingBackend,
    ChunkEmbedding,
    embed_code_chunks,
    save_embeddings,
    load_embeddings,
    create_embedding_backend,
)
from .vector_index import (
    SearchResult,
    VectorIndex,
    NumpyVectorIndex,
    FAISSVectorIndex,
    create_vector_index,
    build_index_from_embeddings,
)
from .batch_mode import (
    BatchExitCode,
    BatchConfig,
    WorkflowResult,
    BatchResult,
    BatchExecutor,
    run_batch_sync,
)
from .secrets_vault import (
    SecretMetadata,
    SecretProvider,
    InMemoryVault,
    EncryptedFileVault,
    AccessPolicy,
    VaultManager,
    create_vault,
)
from .tool_registry import (
    ToolCategory,
    ToolPermission,
    ToolParameter,
    ToolDefinition,
    ToolRegistry,
    get_tool_registry,
)
from .agent_llm_bridge import (
    ExecutionState,
    ToolCall,
    ToolResult,
    ExecutionStep,
    AgentExecutionResult,
    ToolExecutor,
    LLMAgentExecutor,
    create_agent_executor,
)
from .prompt_templates import (
    TaskType,
    FewShotExample,
    PromptTemplate,
    get_template,
    detect_task_type,
    build_prompt,
)
from .bm25_index import (
    BM25Document,
    BM25SearchResult,
    Tokenizer,
    BM25Index,
    build_bm25_index_from_chunks,
)
from .hybrid_search import (
    FusionStrategy,
    HybridSearchResult,
    HybridSearchEngine,
    create_hybrid_search_engine,
)
# Alias for backwards compatibility
create_hybrid_engine = create_hybrid_search_engine
from .workflow_templates import (
    WorkflowParameter,
    WorkflowStep,
    WorkflowTemplate,
    TemplateManager,
    get_template_manager,
    list_builtin_templates,
    BUILTIN_TEMPLATES,
)
from .caching import (
    CacheEntry,
    CacheBackend,
    InMemoryCache,
    DiskCache,
    LLMCache,
    ToolResultCache,
    create_llm_cache,
)
from .graph_executor import StreamEvent
from .monitoring import (
    MetricType,
    HealthStatus,
    Metric,
    HealthCheck,
    MetricsCollector,
    HealthChecker,
    AgentMonitor,
    RateLimiter,
    CircuitBreaker,
    get_metrics,
    get_health_checker,
    get_agent_monitor,
    check_ollama_health,
    check_disk_space,
    check_memory_usage,
)
from .resilience import (
    BackoffStrategy,
    RetryConfig,
    retry,
    retry_async,
    RetryContext,
    FallbackChain,
    Timeout,
    Bulkhead,
    GracefulDegradation,
    with_timeout,
    with_retry,
    with_fallback,
)
from .config import (
    RAGIXConfig,
    LLMConfig,
    MCPConfig,
    SafetyConfig,
    SearchConfig,
    LoggingConfig,
    WebUIConfig,
    load_config,
    save_config,
    get_config,
    reload_config,
    find_config_file,
)
from .log_integrity import (
    LogEntry,
    LogIntegrityReport,
    compute_hash,
    compute_file_hash,
    ChainedLogHasher,
    SimpleFileHasher,
    AuditLogManager,
)
from .plugin_system import (
    PluginType,
    TrustLevel,
    PluginCapability,
    PluginTool,
    PluginWorkflow,
    PluginManifest,
    LoadedPlugin,
    PluginManager,
    get_plugin_manager,
    compute_plugin_checksum,
)
from .swe_workflows import (
    WorkflowState,
    ChunkState,
    ChunkResult,
    WorkflowCheckpoint,
    ChunkConfig,
    ChunkedWorkflow,
    FileProcessingWorkflow,
    CodeReviewWorkflow,
    MigrationWorkflow,
    list_checkpoints,
    resume_workflow,
)
from .sandbox_base import (
    SandboxType,
    SandboxCapability,
    SandboxConfig,
    ExecutionResult,
    BaseSandbox,
    SandboxRegistry,
    HybridSandbox,
    ShellSandboxAdapter,
    create_sandbox,
    get_sandbox_registry,
)
# Import tool registry additions
from .tool_registry import (
    ToolProvider,
    sync_plugins_to_registry,
)
# WASP executor
from .wasp_executor import (
    WaspExecutionResult,
    WaspExecutor,
    get_wasp_executor,
    execute_wasp_action,
)

__all__ = [
    # LLM Backends
    "SovereigntyStatus",
    "BaseLLM",
    "OllamaLLM",
    "ClaudeLLM",
    "OpenAILLM",
    "create_llm_backend",
    "get_backend_from_env",
    "ShellSandbox",
    "CommandResult",
    "AgentLogger",
    "LogLevel",
    "mask_secrets",
    "Profile",
    "compute_dry_run_from_profile",
    "get_profile_restrictions",
    "merge_denylist_from_config",
    "extract_json_object",
    "extract_json_with_diagnostics",
    "validate_action_schema",
    "create_retry_prompt",
    "Retriever",
    "GrepRetriever",
    "RetrievalResult",
    "format_retrieval_results",
    "AgentNode",
    "AgentEdge",
    "AgentGraph",
    "NodeStatus",
    "TransitionCondition",
    "create_linear_workflow",
    "GraphExecutor",
    "SyncGraphExecutor",
    "ExecutionContext",
    "ExecutionResult",
    "ExecutionStatus",
    "BaseAgent",
    "AgentCapability",
    "CodeAgent",
    "DocAgent",
    "GitAgent",
    "TestAgent",
    "ChunkType",
    "CodeChunk",
    "PythonChunker",
    "MarkdownChunker",
    "GenericChunker",
    "chunk_file",
    "EmbeddingBackend",
    "EmbeddingConfig",
    "SentenceTransformerBackend",
    "DummyEmbeddingBackend",
    "ChunkEmbedding",
    "embed_code_chunks",
    "save_embeddings",
    "load_embeddings",
    "create_embedding_backend",
    "SearchResult",
    "VectorIndex",
    "NumpyVectorIndex",
    "FAISSVectorIndex",
    "create_vector_index",
    "build_index_from_embeddings",
    "BatchExitCode",
    "BatchConfig",
    "WorkflowResult",
    "BatchResult",
    "BatchExecutor",
    "run_batch_sync",
    "SecretMetadata",
    "SecretProvider",
    "InMemoryVault",
    "EncryptedFileVault",
    "AccessPolicy",
    "VaultManager",
    "create_vault",
    "ToolCategory",
    "ToolPermission",
    "ToolParameter",
    "ToolDefinition",
    "ToolRegistry",
    "get_tool_registry",
    "ExecutionState",
    "ToolCall",
    "ToolResult",
    "ExecutionStep",
    "AgentExecutionResult",
    "ToolExecutor",
    "LLMAgentExecutor",
    "create_agent_executor",
    "TaskType",
    "FewShotExample",
    "PromptTemplate",
    "get_template",
    "detect_task_type",
    "build_prompt",
    "DANGEROUS_PATTERNS",
    "GIT_DESTRUCTIVE_PATTERNS",
    # BM25 Index
    "BM25Document",
    "BM25SearchResult",
    "Tokenizer",
    "BM25Index",
    "build_bm25_index_from_chunks",
    # Hybrid Search
    "FusionStrategy",
    "HybridSearchResult",
    "HybridSearchEngine",
    "create_hybrid_search_engine",
    "create_hybrid_engine",  # alias
    # Workflow Templates
    "WorkflowParameter",
    "WorkflowStep",
    "WorkflowTemplate",
    "TemplateManager",
    "get_template_manager",
    "list_builtin_templates",
    "BUILTIN_TEMPLATES",
    # Caching
    "CacheEntry",
    "CacheBackend",
    "InMemoryCache",
    "DiskCache",
    "LLMCache",
    "ToolResultCache",
    "create_llm_cache",
    # Streaming
    "StreamEvent",
    # Monitoring
    "MetricType",
    "HealthStatus",
    "Metric",
    "HealthCheck",
    "MetricsCollector",
    "HealthChecker",
    "AgentMonitor",
    "RateLimiter",
    "CircuitBreaker",
    "get_metrics",
    "get_health_checker",
    "get_agent_monitor",
    "check_ollama_health",
    "check_disk_space",
    "check_memory_usage",
    # Resilience
    "BackoffStrategy",
    "RetryConfig",
    "retry",
    "retry_async",
    "RetryContext",
    "FallbackChain",
    "Timeout",
    "Bulkhead",
    "GracefulDegradation",
    "with_timeout",
    "with_retry",
    "with_fallback",
    # Configuration
    "RAGIXConfig",
    "LLMConfig",
    "MCPConfig",
    "SafetyConfig",
    "SearchConfig",
    "LoggingConfig",
    "WebUIConfig",
    "load_config",
    "save_config",
    "get_config",
    "reload_config",
    "find_config_file",
    # Log Integrity
    "LogEntry",
    "LogIntegrityReport",
    "compute_hash",
    "compute_file_hash",
    "ChainedLogHasher",
    "SimpleFileHasher",
    "AuditLogManager",
    # Plugin System
    "PluginType",
    "TrustLevel",
    "PluginCapability",
    "PluginTool",
    "PluginWorkflow",
    "PluginManifest",
    "LoadedPlugin",
    "PluginManager",
    "get_plugin_manager",
    "compute_plugin_checksum",
    # SWE Workflows
    "WorkflowState",
    "ChunkState",
    "ChunkResult",
    "WorkflowCheckpoint",
    "ChunkConfig",
    "ChunkedWorkflow",
    "FileProcessingWorkflow",
    "CodeReviewWorkflow",
    "MigrationWorkflow",
    "list_checkpoints",
    "resume_workflow",
    # Sandbox Abstraction
    "SandboxType",
    "SandboxCapability",
    "SandboxConfig",
    "ExecutionResult",
    "BaseSandbox",
    "SandboxRegistry",
    "HybridSandbox",
    "ShellSandboxAdapter",
    "create_sandbox",
    "get_sandbox_registry",
    # Tool Registry Additions
    "ToolProvider",
    "sync_plugins_to_registry",
    # WASP Executor
    "WaspExecutionResult",
    "WaspExecutor",
    "get_wasp_executor",
    "execute_wasp_action",
]
